from __future__ import unicode_literals


nations = [
{'name':'Gabon', 'url':'https://en.wikipedia.org/wiki/Gabon'},
{'name':'Colombia', 'url':'https://en.wikipedia.org/wiki/Colombia'},
{'name':'Montenegro', 'url':'https://en.wikipedia.org/wiki/Montenegro'},
{'name':'Belarus', 'url':'https://en.wikipedia.org/wiki/Belarus'},
{'name':'Bosnia and Herzegovina', 'url':'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina'},
{'name':'North Korea', 'url':'https://en.wikipedia.org/wiki/North_Korea'},
{'name':'Niue', 'url':'https://en.wikipedia.org/wiki/Niue'},
{'name':'Trinidad and Tobago', 'url':'https://en.wikipedia.org/wiki/Trinidad_and_Tobago'},
{'name':'Republic of the Congo', 'url':'https://en.wikipedia.org/wiki/Republic_of_the_Congo'},
{'name':'Laos', 'url':'https://en.wikipedia.org/wiki/Laos'},
{'name':'Sweden', 'url':'https://en.wikipedia.org/wiki/Sweden'},
{'name':'Chile', 'url':'https://en.wikipedia.org/wiki/Chile'},
{'name':'Senegal', 'url':'https://en.wikipedia.org/wiki/Senegal'},
{'name':'Iran', 'url':'https://en.wikipedia.org/wiki/Iran'},
{'name':'Paraguay', 'url':'https://en.wikipedia.org/wiki/Paraguay'},
{'name':'Benin', 'url':'https://en.wikipedia.org/wiki/Benin'},
{'name':'Andorra', 'url':'https://en.wikipedia.org/wiki/Andorra'},
{'name':'Jordan', 'url':'https://en.wikipedia.org/wiki/Jordan'},
{'name':'Syria', 'url':'https://en.wikipedia.org/wiki/Syria'},
{'name':'Ghana', 'url':'https://en.wikipedia.org/wiki/Ghana'},
{'name':'Vatican City', 'url':'https://en.wikipedia.org/wiki/Vatican_City'},
{'name':'Sri Lanka', 'url':'https://en.wikipedia.org/wiki/Sri_Lanka'},
{'name':'Panama', 'url':'https://en.wikipedia.org/wiki/Panama'},
{'name':'Solomon Islands', 'url':'https://en.wikipedia.org/wiki/Solomon_Islands'},
{'name':'Latvia', 'url':'https://en.wikipedia.org/wiki/Latvia'},
{'name':'Samoa', 'url':'https://en.wikipedia.org/wiki/Samoa'},
{'name':'Guinea', 'url':'https://en.wikipedia.org/wiki/Guinea'},
{'name':'Lesotho', 'url':'https://en.wikipedia.org/wiki/Lesotho'},
{'name':'Lebanon', 'url':'https://en.wikipedia.org/wiki/Lebanon'},
{'name':'Cameroon', 'url':'https://en.wikipedia.org/wiki/Cameroon'},
{'name':'Bhutan', 'url':'https://en.wikipedia.org/wiki/Bhutan'},
{'name':'Turkmenistan', 'url':'https://en.wikipedia.org/wiki/Turkmenistan'},
{'name':'Brunei', 'url':'https://en.wikipedia.org/wiki/Brunei'},
{'name':'Gambia', 'url':'https://en.wikipedia.org/wiki/The_Gambia'},
{'name':'Eritrea', 'url':'https://en.wikipedia.org/wiki/Eritrea'},
{'name':'Iceland', 'url':'https://en.wikipedia.org/wiki/Iceland'},
{'name':'Estonia', 'url':'https://en.wikipedia.org/wiki/Estonia'},
{'name':'Uruguay', 'url':'https://en.wikipedia.org/wiki/Uruguay'},
{'name':'Yemen', 'url':'https://en.wikipedia.org/wiki/Yemen'},
{'name':'Burundi', 'url':'https://en.wikipedia.org/wiki/Burundi'},
{'name':'Russia', 'url':'https://en.wikipedia.org/wiki/Russia'},
{'name':'Ethiopia', 'url':'https://en.wikipedia.org/wiki/Ethiopia'},
{'name':'Fiji', 'url':'https://en.wikipedia.org/wiki/Fiji'},
{'name':'Dominica', 'url':'https://en.wikipedia.org/wiki/Dominica'},
{'name':'Haiti', 'url':'https://en.wikipedia.org/wiki/Haiti'},
{'name':'Norway', 'url':'https://en.wikipedia.org/wiki/Norway'},
{'name':'Hungary', 'url':'https://en.wikipedia.org/wiki/Hungary'},
{'name':'Tuvalu', 'url':'https://en.wikipedia.org/wiki/Tuvalu'},
{'name':'Macedonia', 'url':'https://en.wikipedia.org/wiki/Republic_of_Macedonia'},
{'name':'South Korea', 'url':'https://en.wikipedia.org/wiki/South_Korea'},
{'name':'Qatar', 'url':'https://en.wikipedia.org/wiki/Qatar'},
{'name':'Myanmar', 'url':'https://en.wikipedia.org/wiki/Myanmar'},
{'name':'South Africa', 'url':'https://en.wikipedia.org/wiki/South_Africa'},
{'name':'Nauru', 'url':'https://en.wikipedia.org/wiki/Nauru'},
{'name':'Ivory Coast', 'url':'https://en.wikipedia.org/wiki/Ivory_Coast'},
{'name':'Cyprus', 'url':'https://en.wikipedia.org/wiki/Cyprus'},
{'name':'Sierra Leone', 'url':'https://en.wikipedia.org/wiki/Sierra_Leone'},
{'name':'Georgia', 'url':'https://en.wikipedia.org/wiki/Georgia_(country)'},
{'name':'Botswana', 'url':'https://en.wikipedia.org/wiki/Botswana'},
{'name':'Uganda', 'url':'https://en.wikipedia.org/wiki/Uganda'},
{'name':'Guatemala', 'url':'https://en.wikipedia.org/wiki/Guatemala'},
{'name':'Nicaragua', 'url':'https://en.wikipedia.org/wiki/Nicaragua'},
{'name':'Kuwait', 'url':'https://en.wikipedia.org/wiki/Kuwait'},
{'name':'Zimbabwe', 'url':'https://en.wikipedia.org/wiki/Zimbabwe'},
{'name':'Abkhazia', 'url':'https://en.wikipedia.org/wiki/Abkhazia'},
{'name':'Ecuador', 'url':'https://en.wikipedia.org/wiki/Ecuador'},
{'name':'Comoros', 'url':'https://en.wikipedia.org/wiki/Comoros'},
{'name':'The Bahamas', 'url':'https://en.wikipedia.org/wiki/The_Bahamas'},
{'name':'Saint Lucia', 'url':'https://en.wikipedia.org/wiki/Saint_Lucia'},
{'name':'Dominican Republic', 'url':'https://en.wikipedia.org/wiki/Dominican_Republic'},
{'name':'Grenada', 'url':'https://en.wikipedia.org/wiki/Grenada'},
{'name':'Guyana', 'url':'https://en.wikipedia.org/wiki/Guyana'},
{'name':'Moldova', 'url':'https://en.wikipedia.org/wiki/Moldova'},
{'name':'Marshall Islands', 'url':'https://en.wikipedia.org/wiki/Marshall_Islands'},
{'name':'Sudan', 'url':'https://en.wikipedia.org/wiki/Sudan'},
{'name':'Mozambique', 'url':'https://en.wikipedia.org/wiki/Mozambique'},
{'name':'Egypt', 'url':'https://en.wikipedia.org/wiki/Egypt'},
{'name':'Northern Cyprus', 'url':'https://en.wikipedia.org/wiki/Northern_Cyprus'},
{'name':'Chad', 'url':'https://en.wikipedia.org/wiki/Chad'},
{'name':'Belize', 'url':'https://en.wikipedia.org/wiki/Belize'},
{'name':'United States', 'url':'https://en.wikipedia.org/wiki/United_States'},
{'name':'Saint Kitts and Nevis', 'url':'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis'},
{'name':'Monaco', 'url':'https://en.wikipedia.org/wiki/Monaco'},
{'name':'Singapore', 'url':'https://en.wikipedia.org/wiki/Singapore'},
{'name':'Romania', 'url':'https://en.wikipedia.org/wiki/Romania'},
{'name':'Honduras', 'url':'https://en.wikipedia.org/wiki/Honduras'},
{'name':'Mauritania', 'url':'https://en.wikipedia.org/wiki/Mauritania'},
{'name':'Malawi', 'url':'https://en.wikipedia.org/wiki/Malawi'},
{'name':'Niger', 'url':'https://en.wikipedia.org/wiki/Niger'},
{'name':'Israel', 'url':'https://en.wikipedia.org/wiki/Israel'},
{'name':'Burkina Faso', 'url':'https://en.wikipedia.org/wiki/Burkina_Faso'},
{'name':'Germany', 'url':'https://en.wikipedia.org/wiki/Germany'},
{'name':'Bolivia', 'url':'https://en.wikipedia.org/wiki/Bolivia'},
{'name':'Equatorial Guinea', 'url':'https://en.wikipedia.org/wiki/Equatorial_Guinea'},
{'name':'Angola', 'url':'https://en.wikipedia.org/wiki/Angola'},
{'name':'Liechtenstein', 'url':'https://en.wikipedia.org/wiki/Liechtenstein'},
{'name':'Mexico', 'url':'https://en.wikipedia.org/wiki/Mexico'},
{'name':'Australia', 'url':'https://en.wikipedia.org/wiki/Australia'},
{'name':'S\xc3\xa3o Tom\xc3\xa9 and Pr\xc3\xadncipe', 'url':'https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe'},
{'name':'Italy', 'url':'https://en.wikipedia.org/wiki/Italy'},
{'name':'Tanzania', 'url':'https://en.wikipedia.org/wiki/Tanzania'},
{'name':'Slovenia', 'url':'https://en.wikipedia.org/wiki/Slovenia'},
{'name':'Peru', 'url':'https://en.wikipedia.org/wiki/Peru'},
{'name':'China', 'url':'https://en.wikipedia.org/wiki/China'},
{'name':'Oman', 'url':'https://en.wikipedia.org/wiki/Oman'},
{'name':'Croatia', 'url':'https://en.wikipedia.org/wiki/Croatia'},
{'name':'Luxembourg', 'url':'https://en.wikipedia.org/wiki/Luxembourg'},
{'name':'Argentina', 'url':'https://en.wikipedia.org/wiki/Argentina'},
{'name':'San Marino', 'url':'https://en.wikipedia.org/wiki/San_Marino'},
{'name':'Austria', 'url':'https://en.wikipedia.org/wiki/Austria'},
{'name':'Zambia', 'url':'https://en.wikipedia.org/wiki/Zambia'},
{'name':'Portugal', 'url':'https://en.wikipedia.org/wiki/Portugal'},
{'name':'Saudi Arabia', 'url':'https://en.wikipedia.org/wiki/Saudi_Arabia'},
{'name':'Finland', 'url':'https://en.wikipedia.org/wiki/Finland'},
{'name':'Poland', 'url':'https://en.wikipedia.org/wiki/Poland'},
{'name':'Kiribati', 'url':'https://en.wikipedia.org/wiki/Kiribati'},
{'name':'Papua New Guinea', 'url':'https://en.wikipedia.org/wiki/Papua_New_Guinea'},
{'name':'Maldives', 'url':'https://en.wikipedia.org/wiki/Maldives'},
{'name':'Vanuatu', 'url':'https://en.wikipedia.org/wiki/Vanuatu'},
{'name':'Lithuania', 'url':'https://en.wikipedia.org/wiki/Lithuania'},
{'name':'Kenya', 'url':'https://en.wikipedia.org/wiki/Kenya'},
{'name':'Palestine', 'url':'https://en.wikipedia.org/wiki/State_of_Palestine'},
{'name':'United Arab Emirates', 'url':'https://en.wikipedia.org/wiki/United_Arab_Emirates'},
{'name':'Czech Republic', 'url':'https://en.wikipedia.org/wiki/Czech_Republic'},
{'name':'Slovakia', 'url':'https://en.wikipedia.org/wiki/Slovakia'},
{'name':'Libya', 'url':'https://en.wikipedia.org/wiki/Libya'},
{'name':'Swaziland', 'url':'https://en.wikipedia.org/wiki/Swaziland'},
{'name':'Taiwan', 'url':'https://en.wikipedia.org/wiki/Taiwan'},
{'name':'Somalia', 'url':'https://en.wikipedia.org/wiki/Somalia'},
{'name':'Nepal', 'url':'https://en.wikipedia.org/wiki/Nepal'},
{'name':'Cuba', 'url':'https://en.wikipedia.org/wiki/Cuba'},
{'name':'Azerbaijan', 'url':'https://en.wikipedia.org/wiki/Azerbaijan'},
{'name':'Liberia', 'url':'https://en.wikipedia.org/wiki/Liberia'},
{'name':'India', 'url':'https://en.wikipedia.org/wiki/India'},
{'name':'Iraq', 'url':'https://en.wikipedia.org/wiki/Iraq'},
{'name':'Madagascar', 'url':'https://en.wikipedia.org/wiki/Madagascar'},
{'name':'France', 'url':'https://en.wikipedia.org/wiki/France'},
{'name':'Philippines', 'url':'https://en.wikipedia.org/wiki/Philippines'},
{'name':'Serbia', 'url':'https://en.wikipedia.org/wiki/Serbia'},
{'name':'Bangladesh', 'url':'https://en.wikipedia.org/wiki/Bangladesh'},
{'name':'Vietnam', 'url':'https://en.wikipedia.org/wiki/Vietnam'},
{'name':'Venezuela', 'url':'https://en.wikipedia.org/wiki/Venezuela'},
{'name':'Transnistria', 'url':'https://en.wikipedia.org/wiki/Transnistria'},
{'name':'Nigeria', 'url':'https://en.wikipedia.org/wiki/Nigeria'},
{'name':'Armenia', 'url':'https://en.wikipedia.org/wiki/Armenia'},
{'name':'Turkey', 'url':'https://en.wikipedia.org/wiki/Turkey'},
{'name':'Antigua and Barbuda', 'url':'https://en.wikipedia.org/wiki/Antigua_and_Barbuda'},
{'name':'Barbados', 'url':'https://en.wikipedia.org/wiki/Barbados'},
{'name':'Togo', 'url':'https://en.wikipedia.org/wiki/Togo'},
{'name':'Namibia', 'url':'https://en.wikipedia.org/wiki/Namibia'},
{'name':'South Ossetia', 'url':'https://en.wikipedia.org/wiki/South_Ossetia'},
{'name':'Kazakhstan', 'url':'https://en.wikipedia.org/wiki/Kazakhstan'},
{'name':'Netherlands', 'url':'https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands'},
{'name':'Rwanda', 'url':'https://en.wikipedia.org/wiki/Rwanda'},
{'name':'Saint Vincent and the Grenadines', 'url':'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines'},
{'name':'Cambodia', 'url':'https://en.wikipedia.org/wiki/Cambodia'},
{'name':'Sahrawi Arab Democratic Republic', 'url':'https://en.wikipedia.org/wiki/Sahrawi_Arab_Democratic_Republic'},
{'name':'El Salvador', 'url':'https://en.wikipedia.org/wiki/El_Salvador'},
{'name':'Ukraine', 'url':'https://en.wikipedia.org/wiki/Ukraine'},
{'name':'Costa Rica', 'url':'https://en.wikipedia.org/wiki/Costa_Rica'},
{'name':'Mongolia', 'url':'https://en.wikipedia.org/wiki/Mongolia'},
{'name':'Bulgaria', 'url':'https://en.wikipedia.org/wiki/Bulgaria'},
{'name':'Guinea-Bissau', 'url':'https://en.wikipedia.org/wiki/Guinea-Bissau'},
{'name':'Brazil', 'url':'https://en.wikipedia.org/wiki/Brazil'},
{'name':'South Sudan', 'url':'https://en.wikipedia.org/wiki/South_Sudan'},
{'name':'Kyrgyzstan', 'url':'https://en.wikipedia.org/wiki/Kyrgyzstan'},
{'name':'Afghanistan', 'url':'https://en.wikipedia.org/wiki/Afghanistan'},
{'name':'New Zealand', 'url':'https://en.wikipedia.org/wiki/New_Zealand'},
{'name':'Pakistan', 'url':'https://en.wikipedia.org/wiki/Pakistan'},
{'name':'Belgium', 'url':'https://en.wikipedia.org/wiki/Belgium'},
{'name':'Canada', 'url':'https://en.wikipedia.org/wiki/Canada'},
{'name':'Somaliland', 'url':'https://en.wikipedia.org/wiki/Somaliland'},
{'name':'Kosovo', 'url':'https://en.wikipedia.org/wiki/Kosovo'},
{'name':'Ireland', 'url':'https://en.wikipedia.org/wiki/Republic_of_Ireland'},
{'name':'Tonga', 'url':'https://en.wikipedia.org/wiki/Tonga'},
{'name':'Japan', 'url':'https://en.wikipedia.org/wiki/Japan'},
{'name':'Malta', 'url':'https://en.wikipedia.org/wiki/Malta'},
{'name':'Tajikistan', 'url':'https://en.wikipedia.org/wiki/Tajikistan'},
{'name':'Thailand', 'url':'https://en.wikipedia.org/wiki/Thailand'},
{'name':'Denmark', 'url':'https://en.wikipedia.org/wiki/Denmark'},
{'name':'United Kingdom', 'url':'https://en.wikipedia.org/wiki/United_Kingdom'},
{'name':'Tunisia', 'url':'https://en.wikipedia.org/wiki/Tunisia'},
{'name':'Micronesia', 'url':'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia'},
{'name':'Bahrain', 'url':'https://en.wikipedia.org/wiki/Bahrain'},
{'name':'Democratic Republic of the Congo', 'url':'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'},
{'name':'Djibouti', 'url':'https://en.wikipedia.org/wiki/Djibouti'},
{'name':'Central African Republic', 'url':'https://en.wikipedia.org/wiki/Central_African_Republic'},
{'name':'Palau', 'url':'https://en.wikipedia.org/wiki/Palau'},
{'name':'Algeria', 'url':'https://en.wikipedia.org/wiki/Algeria'},
{'name':'Mauritius', 'url':'https://en.wikipedia.org/wiki/Mauritius'},
{'name':'Cape Verde', 'url':'https://en.wikipedia.org/wiki/Cape_Verde'},
{'name':'Cook Islands', 'url':'https://en.wikipedia.org/wiki/Cook_Islands'},
{'name':'Morocco', 'url':'https://en.wikipedia.org/wiki/Morocco'},
{'name':'Suriname', 'url':'https://en.wikipedia.org/wiki/Suriname'},
{'name':'Jamaica', 'url':'https://en.wikipedia.org/wiki/Jamaica'},
{'name':'Malaysia', 'url':'https://en.wikipedia.org/wiki/Malaysia'},
{'name':'Switzerland', 'url':'https://en.wikipedia.org/wiki/Switzerland'},
{'name':'Albania', 'url':'https://en.wikipedia.org/wiki/Albania'},
{'name':'East Timor', 'url':'https://en.wikipedia.org/wiki/East_Timor'},
{'name':'Uzbekistan', 'url':'https://en.wikipedia.org/wiki/Uzbekistan'},
{'name':'Mali', 'url':'https://en.wikipedia.org/wiki/Mali'},
{'name':'Nagorno-Karabakh', 'url':'https://en.wikipedia.org/wiki/Nagorno-Karabakh_Republic'},
{'name':'Greece', 'url':'https://en.wikipedia.org/wiki/Greece'},
{'name':'Indonesia', 'url':'https://en.wikipedia.org/wiki/Indonesia'},
{'name':'Spain', 'url':'https://en.wikipedia.org/wiki/Spain'},
{'name':'Seychelles', 'url':'https://en.wikipedia.org/wiki/Seychelles'}
]
